services:
  frontend:
    env_file:
      - ../.env
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: remnawave-market-frontend
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      NODE_ENV: production
    networks:
      - remnawave-network

networks:
  remnawave-network:
    external: true
